" vi: ft=vim
 
" Plugins
" {
    let vundle_exists=expand('~/.vim/plugins/download/Vundle.vim')

    if !isdirectory(vundle_exists)
      if !executable("git")
        echoerr "You have to install curl or first install vim-plug yourself!"
        execute "q!"
      endif
      echo "Installing Vundle..."
      echo ""
      silent !\git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/plugins/download/Vundle.vim

      autocmd VimEnter * PluginInstall
    endif

    set nocompatible
    filetype off
    set rtp+=~/.vim/plugins/download/Vundle.vim
    set rtp+=~/.vim/plugins/settings/
    call vundle#begin('$HOME/.vim/plugins/download')

      " let Vundle manage Vundle (required)
      Plugin 'VundleVim/Vundle.vim'

      runtime golang
      runtime common
      runtime js
      runtime rustlang
      runtime python

    call vundle#end()
    filetype plugin indent on

    " Auto indent pasted text
    " {
        nnoremap p p=`]<C-o>
        nnoremap P P=`]<C-o>
        filetype plugin on
        filetype indent on
    " }
" }


" General
" {

    " Encoding
    " {
        set encoding=utf-8
        set fileencoding=utf-8
        set fileencodings=utf-8
        set bomb
        set binary
        set ttyfast
    " }

    " Fix backspace indent
    " {
        set backspace=indent,eol,start
    " }

    " Tabs. May be overriten by autocmd rules
    " {
        set tabstop=4
        set softtabstop=0
        set shiftwidth=4
        set expandtab
    " }

    " Map leader to ,
    " {
        let mapleader=','
    " }

    "" Enable hidden buffers
    " {
        set hidden
    " }


    " Searching
    " {
        set hlsearch
        set incsearch
        set ignorecase
        set smartcase
    " }

    " Directories for swp files
    " {
        set nobackup
        set noswapfile
    " }

    " session management
    " {
        let g:session_directory = "~/.vim/session"
        let g:session_autoload = "no"
        let g:session_autosave = "no"
        let g:session_command_aliases = 1
    " }

    set fileformats=unix,dos,mac

    if exists('$SHELL')
        set shell=$SHELL
    else
        set shell=/bin/sh
    endif
" }


" Visual Settings
" {
    syntax on
    set ruler
    set number

    let no_buffers_menu=1
    if !exists('g:not_finish_vimplug')
      " colorscheme molokai
      colorscheme quantum
      set background=dark
      " set termguicolors
    endif

    set mousemodel=popup
    set t_Co=256
    set guioptions=egmrti
    set gfn=Monospace\ 10

    if has("gui_running")
      if has("gui_mac") || has("gui_macvim")
        set guifont=Menlo:h12
        set transparency=7
      endif
    else
      let g:CSApprox_loaded = 1

      " IndentLine
      let g:indentLine_enabled = 1
      let g:indentLine_concealcursor = 0
      let g:indentLine_char = '┆'
      let g:indentLine_faster = 1


      if $COLORTERM == 'gnome-terminal'
        set term=gnome-256color
      else
        if $TERM == 'xterm'
          set term=xterm-256color
        endif
      endif

    endif


    if &term =~ '256color'
      set t_ut=
    endif


    " Disable the blinking cursor.
    " {
        set gcr=a:blinkon0
        set scrolloff=3
    " }

    " Status bar
    " {
        set laststatus=2
    " }

    " Use modeline overrides
    " {
        set modeline
        set modelines=10

        set title
        set titleold="Terminal"
        set titlestring=%F

        set statusline=%F%m%r%h%w%=(%{&ff}/%Y)\ (line\ %l\/%L,\ col\ %c)\
    " }

    " Search mappings: These will make it so that going to the next one in a
    " search will center on the line it's found in.
    " {
        nnoremap n nzzzv
        nnoremap N Nzzzv
    " }

    if exists("*fugitive#statusline")
      set statusline+=%{fugitive#statusline()}
    endif

    " vim-airline
    " {
        let g:airline_theme = 'powerlineish'
        let g:airline#extensions#syntastic#enabled = 1
        let g:airline#extensions#branch#enabled = 1
        let g:airline#extensions#tabline#enabled = 1
        let g:airline#extensions#tagbar#enabled = 1
        let g:airline_skip_empty_sections = 1
    " }
" }


" Abbreviations
" no one is really happy until you have this shortcuts
" {
    cnoreabbrev W! w!
    cnoreabbrev Q! q!
    cnoreabbrev Qall! qall!
    cnoreabbrev Wq wq
    cnoreabbrev Wa wa
    cnoreabbrev wQ wq
    cnoreabbrev WQ wq
    cnoreabbrev W w
    cnoreabbrev Q q
    cnoreabbrev Qall qall

    " NERDTree configuration
    " {
        let g:NERDTreeChDirMode=2
        let g:NERDTreeIgnore=['\.rbc$', '\~$', '\.pyc$', '\.db$', '\.sqlite$', '__pycache__']
        let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\.bak$', '\~$']
        let g:NERDTreeShowBookmarks=1
        let g:nerdtree_tabs_focus_on_files=1
        let g:NERDTreeMapOpenInTabSilent = '<RightMouse>'
        let g:NERDTreeWinSize = 50
        set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite
        nnoremap <silent> <F2> :NERDTreeFind<CR>
        nnoremap <silent> <F3> :NERDTreeToggle<CR>
    " }

    " grep.vim
    " {
        nnoremap <silent> <leader>f :Rgrep<CR>
        let Grep_Default_Options = '-IR'
        let Grep_Skip_Files = '*.log *.db'
        let Grep_Skip_Dirs = '.git node_modules'
    " }

    " vimshell.vim
    " {
        let g:vimshell_user_prompt = 'fnamemodify(getcwd(), ":~")'
        let g:vimshell_prompt =  '$ '
    " }

    " " terminal emulation
    " " {
    "     if g:vim_bootstrap_editor == 'nvim'
    "       nnoremap <silent> <leader>sh :terminal<CR>
    "     else
    "       nnoremap <silent> <leader>sh :VimShellCreate<CR>
    "     endif
    " " }
" }


" Functions
" {
    if !exists('*s:setupWrapping')
      function s:setupWrapping()
        set wrap
        set wm=2
        set textwidth=79
      endfunction
    endif
" }


" Autocmd Rules
" {
    " The PC is fast enough, do syntax highlight syncing from start unless 200 lines
    " {
        augroup vimrc-sync-fromstart
          autocmd!
          autocmd BufEnter * :syntax sync maxlines=200
        augroup END
    " }

    " Remember cursor position
    " {
        augroup vimrc-remember-cursor-position
          autocmd!
          autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
        augroup END
    " }

    " txt
    " {
        augroup vimrc-wrapping
          autocmd!
          autocmd BufRead,BufNewFile *.txt call s:setupWrapping()
        augroup END
    " }

    " make/cmake
    " {
        augroup vimrc-make-cmake
          autocmd!
          autocmd FileType make setlocal noexpandtab
          autocmd BufNewFile,BufRead CMakeLists.txt setlocal filetype=cmake
        augroup END
    " }
    set autoread
" }



" Mappings
" {
    " Split
    " {
        noremap <Leader>h :<C-u>split<CR>
        noremap <Leader>v :<C-u>vsplit<CR>
    " }

    " Git
    " {
        noremap <Leader>ga :Gwrite<CR>
        noremap <Leader>gc :Gcommit<CR>
        noremap <Leader>gsh :Gpush<CR>
        noremap <Leader>gll :Gpull<CR>
        noremap <Leader>gs :Gstatus<CR>
        noremap <Leader>gb :Gblame<CR>
        noremap <Leader>gd :Gvdiff<CR>
        noremap <Leader>gr :Gremove<CR>
    " }

    " session management
    " {
        nnoremap <leader>so :OpenSession<Space>
        nnoremap <leader>ss :SaveSession<Space>
        nnoremap <leader>sd :DeleteSession<CR>
        nnoremap <leader>sc :CloseSession<CR>
    " }

    " Tabs
    " {
        nnoremap <Tab> gt
        nnoremap <S-Tab> gT
        nnoremap <silent> <S-t> :tabnew<CR>
    " }

    " Set working directory
    " {
        nnoremap <leader>. :lcd %:p:h<CR>
    " }

    " Opens an edit command with the path of the currently edited file filled in
    " {
        noremap <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>
    " }

    " Opens a tab edit command with the path of the currently edited file filled
    " {
        noremap <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>
    " }

    " fzf.vim
    " {
        set wildmode=list:longest,list:full
        set wildignore+=*.o,*.obj,.git,*.rbc,*.pyc,__pycache__
        let $FZF_DEFAULT_COMMAND =  "find * -path '*/\.*' -prune -o -path 'node_modules/**' -prune -o -path 'target/**' -prune -o -path 'dist/**' -prune -o  -type f -print -o -type l -print 2> /dev/null"
    " }

    " The Silver Searcher
    " {
        if executable('ag')
          let $FZF_DEFAULT_COMMAND = 'ag --hidden --ignore .git -g ""'
          set grepprg=ag\ --nogroup\ --nocolor
        endif
    " }

    " ripgrep
    " {
        if executable('rg')
          let $FZF_DEFAULT_COMMAND = 'rg --files --hidden --follow --glob "!.git/*"'
          set grepprg=rg\ --vimgrep
          command! -bang -nargs=* Find call fzf#vim#grep('rg --column --line-number --no-heading --fixed-strings --ignore-case --hidden --follow --glob "!.git/*" --color "always" '.shellescape(<q-args>).'| tr -d "\017"', 1, <bang>0)
        endif
    " }

    cnoremap <C-P> <C-R>=expand("%:p:h") . "/" <CR>
    nnoremap <silent> <leader>b :Buffers<CR>
    nnoremap <silent> <leader>e :FZF -m<CR>

    " snippets
    " {
        let g:UltiSnipsExpandTrigger="<tab>"
        let g:UltiSnipsJumpForwardTrigger="<tab>"
        let g:UltiSnipsJumpBackwardTrigger="<c-b>"
        let g:UltiSnipsEditSplit="vertical"
    " }

    " syntastic
    " {
        let g:syntastic_always_populate_loc_list=1
        let g:syntastic_error_symbol='✗'
        let g:syntastic_warning_symbol='⚠'
        let g:syntastic_style_error_symbol = '✗'
        let g:syntastic_style_warning_symbol = '⚠'
        let g:syntastic_auto_loc_list=1
        let g:syntastic_aggregate_errors = 1
    " }

    " Tagbar
    " {
        nmap <silent> <F4> :TagbarToggle<CR>
        let g:tagbar_autofocus = 1
    " }

    " Disable visualbell
    " {
        set noerrorbells visualbell t_vb=
        if has('autocmd')
          autocmd GUIEnter * set visualbell t_vb=
        endif
    " }

    " Copy/Paste/Cut
    " {
        if has('unnamedplus')
          set clipboard=unnamed,unnamedplus
        endif
    " }

    noremap YY "+y<CR>
    noremap <leader>p "+gP<CR>
    noremap XX "+x<CR>

    if has('macunix')
      " pbcopy for OSX copy/paste
      vmap <C-x> :!pbcopy<CR>
      vmap <C-c> :w !pbcopy<CR><CR>
    endif

    " Buffer nav
    " {
        noremap <leader>z :bp<CR>
        noremap <leader>q :bp<CR>
        noremap <leader>x :bn<CR>
        noremap <leader>w :bn<CR>
    " }

    " Close buffer
    " {
        noremap <leader>c :bd<CR>
    " }

    " Clean search (highlight)
    " {
        nnoremap <silent> <leader><space> :noh<cr>
    " }

    " Switching windows
    " {
        noremap <C-j> <C-w>j
        noremap <C-k> <C-w>k
        noremap <C-l> <C-w>l
        noremap <C-h> <C-w>h
    " }

    " Vmap for maintain Visual Mode after shifting > and <
    " {
        vmap < <gv
        vmap > >gv
    " }

    " Move visual block
    " {
        vnoremap J :m '>+1<CR>gv=gv
        vnoremap K :m '<-2<CR>gv=gv
    " }

    " Open current line on GitHub
    " {
        nnoremap <Leader>o :.Gbrowse<CR>
    " }
" }

" " Custom configs
" " {
"     " go
"     " {
"         " vim-go
"         " run :GoBuild or :GoTestCompile based on the go file
"         function! s:build_go_files()
"           let l:file = expand('%')
"           if l:file =~# '^\f\+_test\.go$'
"             call go#test#Test(0, 1)
"           elseif l:file =~# '^\f\+\.go$'
"             call go#cmd#Build(0)
"           endif
"         endfunction
"
"         let g:go_list_type = "quickfix"
"         let g:go_fmt_command = "goimports"
"         let g:go_fmt_fail_silently = 1
"         let g:syntastic_go_checkers = ['golint', 'govet']
"         let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
"
"         let g:go_highlight_types = 1
"         let g:go_highlight_fields = 1
"         let g:go_highlight_functions = 1
"         let g:go_highlight_methods = 1
"         let g:go_highlight_operators = 1
"         let g:go_highlight_build_constraints = 1
"         let g:go_highlight_structs = 1
"         let g:go_highlight_generate_tags = 1
"         let g:go_highlight_space_tab_error = 0
"         let g:go_highlight_array_whitespace_error = 0
"         let g:go_highlight_trailing_whitespace_error = 0
"         let g:go_highlight_extra_types = 1
"
"         autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4 softtabstop=4
"
"         augroup completion_preview_close
"           autocmd!
"           if v:version > 703 || v:version == 703 && has('patch598')
"             autocmd CompleteDone * if !&previewwindow && &completeopt =~ 'preview' | silent! pclose | endif
"           endif
"         augroup END
"
"         augroup go
"
"           au!
"           au Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
"           au Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
"           au Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
"           au Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')
"
"           au FileType go nmap <Leader>dd <Plug>(go-def-vertical)
"           au FileType go nmap <Leader>dv <Plug>(go-doc-vertical)
"           au FileType go nmap <Leader>db <Plug>(go-doc-browser)
"
"           au FileType go nmap <leader>r  <Plug>(go-run)
"           au FileType go nmap <leader>t  <Plug>(go-test)
"           au FileType go nmap <Leader>gt <Plug>(go-coverage-toggle)
"           au FileType go nmap <Leader>i <Plug>(go-info)
"           au FileType go nmap <silent> <Leader>l <Plug>(go-metalinter)
"           au FileType go nmap <C-g> :GoDecls<cr>
"           au FileType go nmap <leader>dr :GoDeclsDir<cr>
"           au FileType go imap <C-g> <esc>:<C-u>GoDecls<cr>
"           au FileType go imap <leader>dr <esc>:<C-u>GoDeclsDir<cr>
"           au FileType go nmap <leader>rb :<C-u>call <SID>build_go_files()<CR>
"
"         augroup END
"     " }
"
"     " html
"     " {
"         " for html files, 2 spaces
"         " {
"             autocmd Filetype html setlocal ts=2 sw=2 expandtab
"         " }
"     " }
" " }

" " Include user's local vim config
" " {
"     if filereadable(expand("~/.vimrc.local"))
"       source ~/.vimrc.local
"     endif
" " }

" Convenience variables
" {
    " vim-airline
    if !exists('g:airline_symbols')
      let g:airline_symbols = {}
    endif

    if !exists('g:airline_powerline_fonts')
      let g:airline#extensions#tabline#left_sep = ' '
      let g:airline#extensions#tabline#left_alt_sep = '|'
      let g:airline_left_sep          = '▶'
      let g:airline_left_alt_sep      = '»'
      let g:airline_right_sep         = '◀'
      let g:airline_right_alt_sep     = '«'
      let g:airline#extensions#branch#prefix     = '⤴' "➔, ➥, ⎇
      let g:airline#extensions#readonly#symbol   = '⊘'
      let g:airline#extensions#linecolumn#prefix = '¶'
      let g:airline#extensions#paste#symbol      = 'ρ'
      let g:airline_symbols.linenr    = '␊'
      let g:airline_symbols.branch    = '⎇'
      let g:airline_symbols.paste     = 'ρ'
      let g:airline_symbols.paste     = 'Þ'
      let g:airline_symbols.paste     = '∥'
      let g:airline_symbols.whitespace = 'Ξ'
    else
      let g:airline#extensions#tabline#left_sep = ''
      let g:airline#extensions#tabline#left_alt_sep = ''

      " powerline symbols
      let g:airline_left_sep = ''
      let g:airline_left_alt_sep = ''
      let g:airline_right_sep = ''
      let g:airline_right_alt_sep = ''
      let g:airline_symbols.branch = ''
      let g:airline_symbols.readonly = ''
      let g:airline_symbols.linenr = ''
    endif
" }




















































"
" " Settings and scripts for VIM
"
" " General
" " {
"     set nocompatible                "turn off backwards compatibility
"     set backspace=indent,eol,start  "Allow backspace in insert mode
"     set shell=bash
"     autocmd! bufwritepost .vimrc source %
" " }
"
" " Resources
" " {
"     set history=1000                "Store lots of :cmdline history
"     set visualbell                  "No sounds
"     set autoread                    "Reload files changed outside vim
"     set ttyfast                     "Terminal acceleration
"     set viminfo='50,<1000,s100,h
"     set encoding=utf8
"     set path+=**                    "Allow recursive find in current folder
"
"     " Use all the memory needed, for maximum performance.
"     set maxmemtot=2000000
"     set maxmem=2000000
"     set maxmempattern=2000000
" " }
"
" " " Abbreviations
" " " {
" "     iab vdate =getDate()
" "     iab vyear =getYear()
" " " }
"
" " User Interface
" " {
"     " have syntax highlighting in terminals which can display colours:
"     if has('syntax') && (&t_Co > 2)
"       syntax on
"     endif
"
"     " have command-line completion  (for filenames, help topics, option names)
"     " first list the available options and complete the longest common part, then
"     " have further s cycle through the possibilities:
"     set wildmode=list:longest,full
"     " set wildmode=list:longest
"     set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
"     set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing
"     set wildignore+=*vim/backups*
"     set wildignore+=*sass-cache*
"     set wildignore+=*DS_Store*
"     set wildignore+=vendor/rails/**
"     set wildignore+=vendor/cache/**
"     set wildignore+=*.gem
"     set wildignore+=log/**
"     set wildignore+=tmp/**
"     set wildignore+=*.png,*.jpg,*.gif
"
"     set cursorline
"     set number                                          " Line numbers are good
"     set gcr=a:blinkon0                                  " Disable cursor blink
"     set showmode                                        " displays mode in status bar
"     set showcmd                                         " displays partially typed command in the status bar
"     set mouse=a                                         " have the mouse enabled all the time:
"     set ruler                                           " display the current row, col in the status bar
"     set rulerformat=%25([%l,%v]\ %p%%%)    " displays a better format
"
"
"
"     " set smartindent
"     " set smarttab
"     " set paste
"     " nnoremap <F2> :set invpaste paste?<CR>
"     " set pastetoggle=<F2>
"
"
"
"
"     " Show tabs and trailing spaces so I can remove them
"     set list
"     set listchars=tab:»·,trail:·
"     " set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
"
"     " Disable Arrow Keys
"     "
"     " Normal Mode
"     no <down> <Nop>
"     no <left> <Nop>
"     no <right> <Nop>
"     no <up> <Nop>
"
"     " Insert Mode
"     ino <down> <Nop>
"     ino <left> <Nop>
"     ino <right> <Nop>
"     ino <up> <Nop>
"
"     " Visual Mode
"     vno <down> <Nop>
"     vno <left> <Nop>
"     vno <right> <Nop>
"     vno <up> <Nop>
"
" " }
"
" " Auto-complete
" " {
"     " autocomplete funcs and identifiers for languages
"     autocmd FileType php set omnifunc=phpcomplete#CompletePHP
"     autocmd FileType python set omnifunc=pythoncomplete#Complete
"     autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
"     autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
"     autocmd FileType css set omnifunc=csscomplete#CompleteCSS
"     autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
"     autocmd FileType php set omnifunc=phpcomplete#CompletePHP
"     autocmd FileType c set omnifunc=ccomplete#Complete
" " }
"
" " Text Formatting -- General
" " {
"     " don't make it look like there are line breaks where there aren't:
"     set nowrap
"     set shiftround
"     set expandtab
"     set autoindent
"
"     " use spaces instead of tabs
"     set softtabstop=4
"     set tabstop=4
"     set shiftwidth=4
"
"     " normally don't automatically format `text' as it is typed, IE only do this
"     " with comments, at 79 characters:
"     set formatoptions-=t
"     set textwidth=79
"
"     " enable filetype detection:
"     filetype on
"
"     " in human-language files, automatically format everything at 72 chars:
"     autocmd FileType mail,human set formatoptions+=t textwidth=72
"     "
"     " for C-like programming, have automatic indentation:
"     autocmd FileType c,cpp,slang set cindent
"
"     " for actual C (not C++) programming where comments have explicit end
"     " characters, if starting a new line in the middle of a comment automatically
"     " insert the comment leader characters:
"     autocmd FileType c set formatoptions+=ro
"
"     " for Perl programming, have things in braces indenting themselves:
"     autocmd FileType perl set smartindent
"
"     " for CSS, also have things in braces indented:
"     autocmd FileType css set smartindent
"
"     " for HTML, generally format text, but if a long line has been created
"     " leave it alone when editing:
"     autocmd FileType html set formatoptions+=tl
"
"     " for both CSS and HTML, use genuine tab characters for indentation, to
"     " make files a few bytes smaller:
"     autocmd FileType html,css set noexpandtab tabstop=2
"
"     " in makefiles, don't expand tabs to spaces, since actual tab characters
"     " are needed, and have indentation at 8 chars to be sure that all indents
"     " are tabs (despite the mappings later):
"     autocmd FileType make set noexpandtab shiftwidth=8
" " }
"
" " PHP Specific
" " {
"     " highlights interpolated variables in sql strings and does sql-syntax highlighting. yay
"     autocmd FileType php let php_sql_query=1
"
"     " does exactly that. highlights html inside of php strings
"     autocmd FileType php let php_htmlInStrings=1
"
"     " discourages use oh short tags. c'mon its deprecated remember
"     autocmd FileType php let php_noShortTags=1
"
"     " automagically folds functions & methods. this is getting IDE-like isn't it?
"     autocmd FileType php let php_folding=1
"
"     " set "make" command when editing php files
"     set makeprg=php\ -l\ %
"     set errorformat=%m\ in\ %f\ on\ line\ %l
" " }
"
" " Search & Replace
" " {
"
"     " make searches case-insensitive, unless they contain upper-case letters:
"     set ignorecase      " Ignore case when searching...
"     set smartcase       " ...unless we type a capital
"
"     " show the `best match so far' as search strings are typed:
"     set incsearch       " Find the next match as we type the search
"     set hlsearch        " Highlight searches by default
"
"     " assume the /g flag on :s substitutions to replace all matches in a line:
"     set gdefault
" " }
"
" " Navigation / Moving Around *
" " {
"
"     " " use  to cycle through split windows (and + to cycle backwards,
"     " " where possible):
"     " nnoremap  w
"     " nnoremap  W
"
"     " have % bounce between angled brackets, as well as t'other kinds:
"     set matchpairs+=<:>
"
"     " " have Q reformat the current paragraph (or selected text if there is any):
"     " nnoremap Q gqap
"     " vnoremap Q gq
"
"     " " have the usual indentation keystrokes still work in visual mode:
"     " vnoremap  >
"     " vnoremap
"     " vmap
"     " vmap
" " }
"
"
"
"
" " Keystrokes -- For HTML Files
" " {
"     " nnoremap \hc :call InsertCloseTag()
"     " imap  \hca
"     "
"     " nnoremap \hp :call RepeatTag(0)
"     " imap  \hpa
"     "
"     " nnoremap \hn :call RepeatTag(1)
"     " imap  \hna
"
"     " there are other key mappings that it's useful to have for typing HTML
"     " character codes, but that are definitely not wanted in other files (unlike
"     " the above, which won't do any harm), so only map these when entering an HTML
"     " file and unmap them on leaving it:
"     autocmd BufEnter * if &filetype == "html"| call MapHTMLKeys() | endif
" " }
"
" " CTags
" " {
"     command! MakeTags !ctags -R .
" " }
"
" " " User defined functions
" " " {
" "     " Returns the current date
" "     function s:getDate ()
" "         return strftime( "%m-%d-%Y" )
" "     endfunction
" "
" "     "Returns the current year
" "     function s:getYear()
" "         return strftime( "%Y" )
" "     endfunction
" "
" "     " sets up various insert mode key mappings suitable for typing HTML, and
" "     " automatically removes them when switching to a non-HTML buffer
" "     function! MapHTMLKeys(...)
" "
" "       " if no parameter, or a non-zero parameter, set up the mappings:
" "       if a:0 == 0 || a:1 != 0
" "
" "         " require two backslashes to get one:
" "         inoremap \\ \
" "
" "         " then use backslash followed by various symbols insert HTML characters:
" "         inoremap \& &
" "         inoremap \< <
" "         inoremap \> >
" "         inoremap \. ·
" "
" "         " em dash -- have \- always insert an em dash, and also have _ do it if
" "         " ever typed as a word on its own, but not in the middle of other words:
" "         inoremap \- —
" "         iabbrev _ —
" "
" "         " hard space with +Space, and \ for when that doesn't work:
" "         inoremap \
" "         imap  \
" "
" "         " have the normal open and close single quote keys producing the character
" "         " codes that will produce nice curved quotes (and apostophes) on both Unix
" "         " and Windows:
" "         inoremap ` ‘
" "         inoremap ' ’
" "         " then provide the original functionality with preceding backslashes:
" "         inoremap \` `
" "         inoremap \' '
" "
" "         " curved double open and closed quotes (2 and " are the same key for me):
" "         inoremap \2 “
" "         inoremap \" ”
" "
" "         " when switching to a non-HTML buffer, automatically undo these mappings:
" "         autocmd! BufLeave * call MapHTMLKeys(0)
" "
" "       " parameter of zero, so want to unmap everything:
" "       else
" "         iunmap \\
" "         iunmap \&
" "         iunmap \<
" "         iunmap \>
" "         iunmap \-
" "         iunabbrev _
" "         iunmap \
" "         iunmap
" "         iunmap `
" "         iunmap '
" "         iunmap \`
" "         iunmap \'
" "         iunmap \2
" "         iunmap \"
" "
" "         " once done, get rid of the autocmd that called this:
" "         autocmd! BufLeave *
" "
" "       endif " test for mapping/unmapping
" "
" "     endfunction " MapHTMLKeys()
" "
" "     " inserts the appropriate closing HTML tag; used for the \hc operation defined
" "     " above;
" "     " requires ignorecase to be set, or to type HTML tags in exactly the same case
" "     " that I do;
" "     " doesn't treat
" "
" "     " clobbers register z and mark z
" "     "
" "     " by Smylers  http://www.stripey.com/vim/
" "     " 2000 May 4
" "     function! InsertCloseTag()
" "
" "       if &filetype == 'html' || &filetype == 'php'
" "
" "         " list of tags which shouldn't be closed:
" "         let UnaryTags = ' Area Base Br DD DT HR Img Input LI Link Meta P Param '
" "
" "         " remember current position:
" "         normal mz
" "
" "         " loop backwards looking for tags:
" "         let Found = 0
" "         while Found == 0
" "           " find the previous <, then go forwards one character and grab the first
" "           " character plus the entire word:
" "           execute "normal ?\\l"
" "           normal "zyl
" "           let Tag = expand('')
" "
" "           " if this is a closing tag, skip back to its matching opening tag:
" "           if @z == '/'
" "             execute "normal ?\" . Tag . "\"
" "
" "           " if this is a unary tag, then position the cursor for the next
" "           " iteration:
" "           elseif match(UnaryTags, ' ' . Tag . ' ') > 0
" "             normal h
" "
" "           " otherwise this is the tag that needs closing:
" "           else
" "             let Found = 1
" "
" "           endif
" "         endwhile " not yet found match
" "
" "         " create the closing tag and insert it:
" "         let @z = ''
" "         normal `z
" "         if col('.') == 1
" "           normal "zP
" "         else
" "           normal "zp
" "         endif
" "
" "       else " filetype is not HTML
" "         echohl ErrorMsg
" "         echo 'The InsertCloseTag() function is only intended to be used in HTML ' .
" "           \ 'files.'
" "         sleep
" "         echohl None
" "
" "       endif " check on filetype
" "
" "     endfunction " InsertCloseTag()
" "
" "     " repeats a (non-closing) HTML tag from elsewhere in the document; call
" "     " repeatedly until the correct tag is inserted (like with insert mode +P
" "     " and +N completion), with Forward determining whether to copy forwards
" "     " or backwards through the file; used for the \hp and \hn operations defined
" "     " above;
" "     " requires preservation of marks i and j;
" "     " clobbers register z
" "     "
" "     " by Smylers  http://www.stripey.com/vim/
" "     "
" "     " 2000 May 4: for `Vim' 5.6
" "     function! RepeatTag(Forward)
" "
" "       if &filetype == 'html' || &filetype == 'php'
" "
" "         " if the cursor is where this function left it, then continue from there:
" "         if line('.') == line("'i") && col('.') == col("'i")
" "           " delete the tag inserted last time:
" "           if col('.') == strlen(getline('.'))
" "             normal dF<[^/>].\\{-}>\mj\"zyf>`i"
" "         if col('.') == 1
" "           normal "zP
" "         else
" "           normal "zp
" "         endif
" "         normal mi
" "
" "       else " filetype is not HTML
" "         echohl ErrorMsg
" "         echo 'The RepeatTag() function is only intended to be used in HTML files.'
" "         sleep
" "         echohl None
" "
" "       endif
" "
" "     endfunction " RepeatTag()
" "
" "     " Functions for cleaning up tabs and spaces
" "     function! RemoveTrailingSpaces()
" "         %s/\s\+$//
" "     endfunction
" "
" "     function! ConvertTabsToSpaces()
" "         %retab
" "     endfunction
" "
" "     function! CleanFile()
" "         call ConvertTabsToSpaces()
" "         call RemoveTrailingSpaces()
" "     endfunction
" "
" "     " Key binding Ctrl+Shift+f to clean up file
" "     nmap  :call CleanFile()
" "
" "     " Function for toggling search highlighting
" "     function! ToggleHLSearch()
" "         if &hls
" "             set nohls
" "         else
" "             set hls
" "         endif
" "     endfunction
" "
" "     " Key binding Ctrl+Shift+h to toggle search highlighting
" "     nmap  :call ToggleHLSearch()
" " " }
"
"
"
"
"
"
"
"
" if filereadable(expand("~/.vim/templates.vim"))
"     source ~/.vim/templates.vim
" endif
"
" " Plugins
" " {
"     " This loads all the plugins specified in ~/.vim/vundles.vim
"     " Use Vundle plugin to manage all other plugins
"     if filereadable(expand("~/.vim/plugins/main.vim"))
"       source ~/.vim/plugins/main.vim
"     endif
"
"     " Auto indent pasted text
"     nnoremap p p=`]<C-o>
"     nnoremap P P=`]<C-o>
"     filetype plugin on
"     filetype indent on
" " }
