; Global settings
[redshift]
temp-day=5700
temp-night=3500
transition=1
; brightness=0.6
brightness-day=0.8
brightness-night=0.6
; gamma=0.8:0.7:0.8
gamma-day=0.8:0.7:0.8
; gamma-night=0.6
location-provider=manual
; adjustment-method=vidmode
adjustment-method=randr

; The location provider and adjustment method settings
; are in their own sections.
[manual]
lat=51.376495
lon=-0.100594

; In this example screen 1 is adjusted by vidmode. Note
; that the numbering starts from 0, so this is actually
; the second screen.
[vidmode]
screen=1
